DROP TABLE IF EXISTS Records;
CREATE TABLE Records (
	id	        INTEGER NOT NULL,
	username	TEXT NOT NULL,
	bestScore	INTEGER NOT NULL DEFAULT 0,
	bestTime	INTEGER NOT NULL DEFAULT 0,
	lives	    INTEGER NOT NULL DEFAULT 0,
	kills	    INTEGER NOT NULL DEFAULT 0,
	deaths	    INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);